# Generated by Django 2.1.5 on 2019-03-13 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adherent',
            name='prenom',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
