# Generated by Django 2.1.5 on 2019-03-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190313_2204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('adherent', 'sport')},
        ),
    ]
