# Generated by Django 2.1.5 on 2019-03-15 18:56

from django.db import migrations


def load_data(apps, schema_editor):
    Sport = apps.get_model('main_app', 'Sport')
    Sport(designation='March', tarif=1000).save()
    Sport(designation='Jogging', tarif=1500).save()
    Sport(designation='Foot', tarif=5000).save()
    Sport(designation='Tennis', tarif=10000).save()
    Sport(designation='Natation', tarif=12000).save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0003_auto_20190313_2217'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
